ccb_web/Models/Matricula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ccb_web.Models
{
    public class Matricula
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Obrigatório")]
        public int AlunoId { get; set; }
        public int? TurmaId { get; set; }
        public int AnoLetivoId { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataCadastro { get; set; }

        [ForeignKey("AlunoId")]
        public virtual Aluno Aluno { get; set; }
        [ForeignKey("TurmaId")]
        public virtual Turma Turma { get; set; }
        [ForeignKey("AnoLetivoId")]
        public virtual AnoLetivo AnoLetivo { get; set; }


        public virtual ICollection<Conceito> Conceitos { get; set; } 

    }
}

ccb_web/Controllers/MatriculaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ccb_web.Models;
using PagedList;

namespace ccb_web.Controllers
{
    [Authorize]
    public class MatriculaController : Controller
    {
        readonly Contexto _banco = new Contexto();

        public ActionResult Index(int? pagina)
        {
            const int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;

            var matricula = _banco.Matriculas.Include(x => x.Aluno).Include(x => x.Turma).OrderByDescending(x => x.DataCadastro).ToList();

            return View(matricula.ToPagedList(numeroPagina, tamanhoPagina));
        }

        public ActionResult Adicionar()
        {
            var alunos = (from al in _banco.Alunos
                          join mat in _banco.Matriculas on al.Id equals mat.AlunoId
                          into aluno
                          from mat in aluno.DefaultIfEmpty()
                          where al.Id != mat.AlunoId || mat.TurmaId == null
                          select al).ToList();

            ViewBag.AlunoId = new SelectList(alunos, "Id", "Nome");
            ViewBag.TurmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma");
            ViewBag.AnoLetivoId = new SelectList(_banco.AnoLetivos, "Id", "Ano");

            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Matricula novaMatriculaAluno)
        {
            if (ModelState.IsValid)
            {
                _banco.Matriculas.Add(novaMatriculaAluno);
                _banco.SaveChanges();
            }

            var aluno = _banco.Alunos.FirstOrDefault(x => x.Id == novaMatriculaAluno.AlunoId);

            var disciplinas = (from d in _banco.Disciplinas
                               join dpt in _banco.DisciplinaDoProfessoresNasTurmas on d.Id equals dpt.DisciplinaId
                               where d.Id == dpt.DisciplinaId && dpt.TurmaId == novaMatriculaAluno.TurmaId
                               select d).ToList();


            var mat = _banco.Matriculas.FirstOrDefault(x => x.AlunoId == aluno.Id);

            var con = _banco.Conceitos.FirstOrDefault(x => x.MatriculaId == mat.Id);

            if (mat != null && con == null)
            {
                var conceito = new Conceito
                {
                    MatriculaId = mat.Id
                };
                //matricular nas disciplinas da turma
                foreach (var d in disciplinas)
                {
                    conceito.DisciplinaId = d.Id;
                    _banco.Conceitos.Add(conceito);
                    _banco.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            ViewBag.AlunoId = new SelectList(_banco.Alunos, "Id", "Nome", novaMatriculaAluno.AlunoId);
            ViewBag.TurmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma", novaMatriculaAluno.TurmaId);

            return View(novaMatriculaAluno);
        }//fim adicionar

        [HttpGet]
        public ActionResult AdicionarComId(long id)
        {

            var aluno = _banco.Alunos.FirstOrDefault(x => x.Id == id);

            if (aluno != null)
            {
                ViewBag.AlunoId = aluno.Id;
                ViewBag.NomeAluno = aluno.Nome;
            }
            ViewBag.TurmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma");
            ViewBag.AnoLetivoId = new SelectList(_banco.AnoLetivos, "Id", "Ano");

            return View();


        }

        [HttpPost]
        public ActionResult AdicionarComId(Matricula novaMatriculaAluno)
        {
            if (ModelState.IsValid)
            {
                _banco.Matriculas.Add(novaMatriculaAluno);
                _banco.SaveChanges();
            }

            var aluno = _banco.Alunos.FirstOrDefault(x => x.Id == novaMatriculaAluno.AlunoId);

            var disciplinas = (from d in _banco.Disciplinas
                               join dpt in _banco.DisciplinaDoProfessoresNasTurmas on d.Id equals dpt.DisciplinaId
                               where d.Id == dpt.DisciplinaId && dpt.TurmaId == novaMatriculaAluno.TurmaId
                               select d).ToList();


            var mat = _banco.Matriculas.FirstOrDefault(x => x.AlunoId == aluno.Id);

            var con = _banco.Conceitos.FirstOrDefault(x => x.MatriculaId == mat.Id);

            if (mat != null && con == null)
            {
                var conceito = new Conceito
                {
                    MatriculaId = mat.Id
                };

                foreach (var d in disciplinas)
                {
                    conceito.DisciplinaId = d.Id;
                    _banco.Conceitos.Add(conceito);
                    _banco.SaveChanges();
                }
                return RedirectToAction("Index");
            }


            if (aluno != null) ViewBag.NomeAluno = aluno.Nome;
            ViewBag.AlunoId = novaMatriculaAluno.AlunoId;
            ViewBag.TurmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma", novaMatriculaAluno.TurmaId);

            return View(novaMatriculaAluno);
        }//fim adicionar

        [HttpGet]
        public ActionResult GerenciarMatriculas(int? turmaId, int? anoLetivoId)
        {
            ViewBag.turmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma");
            ViewBag.anoLetivoId = new SelectList(_banco.AnoLetivos, "Id", "Ano");

            if (turmaId != null) { ViewBag.turmaSelecionada = turmaId; }
            if (anoLetivoId != null) { ViewBag.anoLetivoselecionado = anoLetivoId; }


            ViewBag.NaoMatriculados = (from al in _banco.Alunos
                                       join mat in _banco.Matriculas on al.Id equals mat.AlunoId
                                       into aluno
                                       from mat in aluno.DefaultIfEmpty()
                                       where al.Id != mat.AlunoId || mat.TurmaId == null
                                       select al).OrderBy(x => x.Nome).ToList();

            var matriculados =
                (from al in _banco.Alunos
                 join mat in _banco.Matriculas on al.Id equals mat.AlunoId
                 where al.Id == mat.AlunoId && mat.TurmaId != null && mat.TurmaId == turmaId
                 select al).OrderBy(x => x.Nome).ToList();

            ViewBag.Matriculados = matriculados;

            var turma = _banco.Turmas.FirstOrDefault(x => x.Id == turmaId);

            if (turma != null)
            {
                ViewBag.QtdAluno = Convert.ToInt32(turma.QtdAlunos);

                ViewBag.QtdVagas = ViewBag.QtdAluno - matriculados.Count;
            }
            
            return View();
        }

        [HttpPost]
        public ActionResult Enturmar(int turmaSelecionada, int anoLetivoselecionado, List<int> alunos)
        {
            if(alunos == null)
            {
                return RedirectToAction("GerenciarMatriculas", new { turmaId = turmaSelecionada, anoLetivoId = anoLetivoselecionado });
            }

            var novaMatricula = new Matricula
            {
                TurmaId = turmaSelecionada,
                AnoLetivoId = anoLetivoselecionado
            };

            var matriculasSemTurma = _banco.Matriculas.Where(x => x.TurmaId == null).ToList();

            var matriculadosSemTurma = (from mat in _banco.Matriculas
                                        join al in alunos on mat.AlunoId equals al
                                        where mat.TurmaId == null && mat.AlunoId == al
                                        select al).ToList();

            var semMatricula = (from al in _banco.Alunos
                                join mat in _banco.Matriculas on al.Id equals mat.AlunoId
                                into aluno
                                from mat in aluno.DefaultIfEmpty()
                                join selecao in alunos on al.Id equals selecao
                                where al.Id == selecao && al.Id != mat.AlunoId
                                select selecao).ToList();

            if (matriculadosSemTurma.Count != 0)
            {
                foreach (var i in matriculadosSemTurma)
                {
                    foreach (var matriculado in matriculasSemTurma)
                    {
                        if (i == matriculado.AlunoId)
                        {
                            matriculado.TurmaId = turmaSelecionada;
                            _banco.Entry(matriculado).State = EntityState.Modified;
                            _banco.SaveChanges();
                        }
                    }

                }

            }

            if (semMatricula.Count != 0)
            {
                var disciplinas = (from d in _banco.Disciplinas
                                   join dpt in _banco.DisciplinaDoProfessoresNasTurmas on d.Id equals dpt.DisciplinaId
                                   where d.Id == dpt.DisciplinaId && dpt.TurmaId == turmaSelecionada
                                   select d).ToList();


                foreach (var i in semMatricula)
                {
                    novaMatricula.AlunoId = i;
                    _banco.Matriculas.Add(novaMatricula);
                    _banco.SaveChanges();
                }


                foreach (var i in semMatricula)
                {
                    

                    var mat = _banco.Matriculas.FirstOrDefault(x => x.AlunoId == i);
                    if (mat != null)
                    {
                        var conceito = new Conceito
                        {
                            MatriculaId = mat.Id
                        };

                        foreach (var d in disciplinas)
                        {
                            conceito.DisciplinaId = d.Id;
                            _banco.Conceitos.Add(conceito);
                            _banco.SaveChanges();
                        }

ccb_web/Views/Matricula/Adicionar.cshtml
@model ccb_web.Models.Matricula

@{
    ViewBag.Title = "Adicionar";
}

<script type="text/javascript">
    $(function () {
        $('.ajuda-data').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
        });

    });
</script>
<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Matricula</strong>
</div>

<div class="panel-body">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Aluno.Nome)
        </div>
        <div class="editor-field">
            @Html.DropDownList("AlunoId", (SelectList)ViewBag.AlunoId, "SELECIONE O ALUNO", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AlunoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Turma.NomeTurma)
        </div>
        <div class="editor-field">
            @Html.DropDownList("TurmaId", (SelectList)ViewBag.TurmaId, "SELECIONE A TURMA", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TurmaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnoLetivo.Ano)
        </div>
        <div class="editor-field">
            @Html.DropDownList("AnoLetivoId", (SelectList)ViewBag.AnoLetivoId, "SELECIONE O ANO", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TurmaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCadastro)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.DataCadastro, new { @class = "form-control ajuda-data" })
            @Html.ValidationMessageFor(model => model.DataCadastro)
        </div>


        <div class="row">
            <hr />
            <div class="col-sm-3 col-sm-offset-6">
                <a class="btn btn-block btn-lg btn-danger" href="@Url.Action("Index", "Matricula")"><span class="glyphicon glyphicon-remove"></span>Cancelar</a>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-block btn-lg btn-success" value="Adicionar"><span class="glyphicon glyphicon-floppy-disk"></span>Cadastrar</button>
            </div>
        </div>
    
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryform")
    @Scripts.Render("~/Scripts/bootstrap-tooltip.js")
}

ccb_web/Views/Matricula/AdicionarComId.cshtml
@model ccb_web.Models.Matricula

@{
    ViewBag.Title = "AdicionarComId";
}

<script>
    $(function ($) {
        $(".input-group-addon").tooltip();
    });


    $(function () {
        $('.ajuda-data').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
        });

    });

    jQuery(function ($) {
        $("#DataCadastro").mask("99/99/9999");
    });

</script>

<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Matricula</strong>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="panel-body">
        <div class="text-center">
            <h3>@ViewBag.NomeAluno</h3>
            @Html.Hidden("AlunoId")
            @Html.ValidationMessageFor(model => model.AlunoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Turma.NomeTurma)
        </div>
        <div class="editor-field">
            @Html.DropDownList("TurmaId", (SelectList)ViewBag.TurmaId, "SELECIONE A TURMA", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TurmaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnoLetivo.Ano)
        </div>
        <div class="editor-field">
            @Html.DropDownList("AnoLetivoId", (SelectList)ViewBag.AnoLetivoId, "SELECIONE O ANO", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AnoLetivoId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCadastro)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.DataCadastro, new { @class = "form-control ajuda-data" })
            @Html.ValidationMessageFor(model => model.DataCadastro)
        </div>

        <div class="row">
            <hr />
            <div class="col-xs-6 col-md-3 col-md-offset-6">
                <a class="btn btn-block btn-lg btn-danger" href="@Url.Action("Index", "Matricula")"><span class="glyphicon glyphicon-remove"></span>Cancelar</a>
            </div>
            <div class="col-xs-6 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-success" value=""><span class="glyphicon glyphicon-floppy-disk"></span>Cadastrar</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryform")
    @Scripts.Render("~/Scripts/jquery.maskedinput.min.js")
}

ccb_web/Views/Matricula/Editar.cshtml
@model ccb_web.Models.Matricula


<script>
    $(function () {
        $('#AnoLetivoId').val("@Model.AnoLetivoId");
        $('#TurmaId').val("@Model.TurmaId");
    });

    $(function () {
        $('.ajuda-data').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
        });

    });
</script>


@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutPadrao.cshtml";
}

<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Matricula</strong>
</div>

<h2>Editar</h2>

<div class="panel-body">



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.AlunoId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Aluno.Nome)
        </div>
        <div class="editor-field">
            @Html.DisplayFor(model => model.Aluno.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Turma.NomeTurma)
        </div>
        <div class="editor-field">
            @Html.DropDownList("TurmaId", (SelectList)ViewBag.TurmaId, "SELECIONE A TURMA", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TurmaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnoLetivo.Ano)
        </div>
        <div class="editor-field">
            @Html.DropDownList("AnoLetivoId", (SelectList)ViewBag.AnoLetivoId, "SELECIONE O ANO", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TurmaId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCadastro)
        </div>
        <div class="editor-field">
            <input type="text" class="form-control ajuda-data" id="DataCadastro" name="DataCadastro" value="@ViewBag.DataCadastro"/>
            @Html.ValidationMessageFor(model => model.DataCadastro)
        </div>

        <div class="row">
            <hr />
            <div class="col-sm-3 col-sm-offset-6">
                <a class="btn btn-block btn-lg btn-danger" href="@Url.Action("Index", "Matricula")"><span class="glyphicon glyphicon-remove"></span>Cancelar</a>
            </div>
            <div class="col-sm-3">
                <button type="submit" class="btn btn-block btn-lg btn-success" value="Adicionar"><span class="glyphicon glyphicon-floppy-disk"></span>Cadastrar</button>
            </div>
        </div>
    
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryform")
    @Scripts.Render("~/Scripts/jquery.maskedinput.min.js")
}

ccb_web/Views/Matricula/GerenciarMatriculas.cshtml
@using ccb_web.Models
@using Microsoft.Ajax.Utilities
@{
    ViewBag.Title = "GerenciarMatriculas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    $(document).ready(function () {
        $('#turmaId').addClass("form-control");
        $('#anoLetivoId').addClass("form-control");
    });


</script>

<strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Gerenciar Matriculas</strong>

<div class="col-md-12">
    <div class="row">
        @using (@Html.BeginForm("GerenciarMatriculas", "Matricula", FormMethod.Get))
            {
            <div class="col-sm-5">
                <label>Turma </label>
                @Html.DropDownList("turmaId", (SelectList)ViewBag.TurmaId, "Selecione a turma", new { onchange = "this.form.submit();" })
            </div>
                <div class="col-sm-2">
                    <label>Ano </label>
                    @Html.DropDownList("anoLetivoId", (SelectList)ViewBag.AnoLetivoId, new { onchange = "this.form.submit();" })
                </div>
                <div class="col-sm-3">
                    <label>Total de Vagas: </label>
                    @ViewBag.QtdAluno<br />
                    <label>Vagas Abertas: </label>
                    @ViewBag.QtdVagas
                </div>
        }
    </div>
    <br />
</div>
@if (ViewBag.turmaSelecionada != null)
{

    using (@Html.BeginForm("Enturmar", "Matricula", FormMethod.Post))
    {
        <div class="col-sm-6">
            <div class="panel panel-success">
                @Html.Hidden("turmaSelecionada")
                @Html.Hidden("anoLetivoselecionado")

                <div class="panel-heading">
                    <h4>Sem Matricula </h4>
                </div>
                <div class="panel-body" style="height: 300px; overflow: scroll">
                    <table class="table table-hover">
                        <tr>
                            <th>
                                <span class="glyphicon glyphicon-ok"></span>
                            </th>
                            <th>
                                Nome do Aluno
                            </th>
                            <th>
                                Sexo
                            </th>
                        </tr>
                        @foreach (var item in @ViewBag.NaoMatriculados)
                        {
                        <tr>
                            <td>
                                <input type="checkbox" value="@item.Id" name="alunos" />
                            </td>
                            <td>
                                @item.Nome
                            </td>
                            <td>
                                @item.Sexo
                            </td>
                        </tr>

                        }
                    </table>
                </div>

                <div class="panel-footer">
                    <input type="submit" class="btn btn-success btn-block" value="Entumar" />
                </div>

            </div>
        </div>

    }

    using (@Html.BeginForm("Desenturmar", "Matricula", FormMethod.Post))
    {

        <div class="col-sm-6">
            <div class="panel panel-success">
                @Html.Hidden("turmaSelecionada")
                @Html.Hidden("anoLetivoselecionado")

                <div class="panel-heading">
                    <h4>Alunos Matriculados </h4>
                </div>

                <div class="panel-body" style="height: 300px; overflow: scroll">
                    <table class="table table-hover">
                        <tr>
                            <th>
                                <span class="glyphicon glyphicon-remove"></span>
                            </th>
                            <th>
                                Nome do Aluno
                            </th>
                            <th>
                                Sexo
                            </th>
                        </tr>
                        @foreach (var item in @ViewBag.Matriculados)
                        {
                        <tr>
                            <td>
                                <input type="checkbox" value="@item.Id" name="alunos" />
                            </td>
                            <td>
                                @item.Nome
                            </td>
                            <td>
                                @item.Sexo
                            </td>
                        </tr>

                        }
                    </table>
                </div>
                <div class="bottom panel-footer ">
                    <input type="submit" class="btn btn-danger btn-block" value="Dentumar" />
                </div>
            </div>
        </div>

    }
}

<script src="/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="/Scripts/jquery.validate.js"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="/Scripts/jquery.maskedinput.js"></script>
<script src="/Scripts/methods_pt.js"></script>

ccb_web/Views/Matricula/Index.cshtml
@model PagedList.IPagedList<ccb_web.Models.Matricula>
@using PagedList.Mvc

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPadrao.cshtml";
}

<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Matricula</strong>
</div>

<div class="panel-body panel-scroll">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <p>
                <a href="@Url.Action("Adicionar", "Matricula")" class="btn btn-block btn-lg btn-success"><span class="glyphicon glyphicon-plus"></span>Nova Matricula</a>
            </p>
            <div class=" panel panel-success">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-4">
                            <h4>Alunos Matriculados</h4>
                        </div>
                    </div>
                </div>
                <table class="table table-hover">
                    <tr>
                        <th>Nome Aluno
                        </th>
                        <th>Nome Turma
                        </th>
                        <th>Data Cadastro
                        </th>

                        <th>AÇÕES
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Aluno.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Turma.NomeTurma)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataCadastro)
                            </td>

                            <td>
                                <a class="btn btn-default" title="Editar" href="@Url.Action("Editar", "Matricula", new {id = item.Id})">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </a>

                                <a class="btn btn-default" title="Detalhes" href="@Url.Action("Detalhes", "Matricula", new {id = item.Id})">
                                    <span class="glyphicon glyphicon-list-alt"></span>
                                </a>

                                <a class="btn btn-primary btn-danger confirm" title="Excluir" href="@Url.Action("Excluir", "Matricula", new {id = item.Id})">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>

                            </td>
                        </tr>
                    }

                </table>
                <div class="panel-footer">
                    <div class=" text-center">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { pagina = page }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery.confirm.js"></script>
<script>
    $(".confirm").confirm({
        text: "Tem certeza que deseja excluir?",
        confirmButton: "Sim",
        cancelButton: "Não"
    });
</script>