ccb_web/Models/Conceito.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ccb_web.Models
{
    public class Conceito
    {
        [Key]
        public int Id { get; set; }
        public int DisciplinaId { get; set; }
        public int MatriculaId { get; set; }

        public string Conceito1Bim { get; set; }
        public string Conceito2Bim { get; set; }
        public string Conceito3Bim { get; set; }
        public string Conceito4Bim { get; set; }
        public string ConceitoFinal { get; set; }

        public string Faltas1Bim { get; set; }
        public string Faltas2Bim { get; set; }
        public string Faltas3Bim { get; set; }
        public string Faltas4Bim { get; set; }
        public string FaltasTotal { get; set; }

        public string Situacao { get; set; }




        [ForeignKey("DisciplinaId")]
        public virtual Disciplina Disciplina { get; set; }
        [ForeignKey("MatriculaId")]
        public virtual Matricula Matricula { get; set; }
       

    }
}

ccb_web/Controllers/ConceitoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using PagedList;
using System.Web.Mvc;
using ccb_web.Models;

namespace ccb_web.Controllers
{
    [Authorize]
    public class ConceitoController : Controller
    {
        readonly Contexto _banco = new Contexto();

        public ActionResult ListaAluno(int? pagina)
        {
            const int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;

            var aluno = _banco.Matriculas.Where(x=> x.TurmaId != null).OrderBy(x => x.Aluno.Nome).ToPagedList(numeroPagina, tamanhoPagina);

            return View(aluno);
        }

        [HttpPost]
        public ActionResult ListaAluno(string termoBusca, int? pagina)
        {
            const int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;

            var aluno = _banco.Matriculas.OrderBy(x => x.Aluno.Nome).ToPagedList(numeroPagina, tamanhoPagina);

            if (!String.IsNullOrEmpty(termoBusca))
            {
                aluno = _banco.Matriculas.OrderBy(x => x.Aluno.Nome).
                Where(x => x.Aluno.Nome.ToUpper().Contains(termoBusca.ToUpper())).
                ToPagedList(numeroPagina, tamanhoPagina);
            }

            return View(aluno);
        }

        public JsonResult GetAlunos(string term)
        {
            var aluno = _banco.Matriculas.Where(x => x.Aluno.Nome.ToUpper().Contains(term.ToUpper()))
                .Select(y => y.Aluno.Nome).ToList();

            return Json(aluno, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult NotaAluno(int? alunoId, int? periodo)
        {
            List<Conceito> conceitos = null;

            if (periodo != null)
            {
                conceitos = _banco.Conceitos.Where(x => x.Matricula.AlunoId == alunoId).ToList();

                foreach (var item in conceitos)
                {
                    switch (periodo)
                    {
                        case 1:
                            ViewBag.Nota = item.Conceito1Bim; ViewBag.Falta = item.Faltas1Bim;
                            break;
                        case 2:
                            ViewBag.Nota = item.Conceito2Bim; ViewBag.Falta = item.Faltas2Bim;
                            break;
                        case 3:
                            ViewBag.Nota = item.Conceito3Bim; ViewBag.Falta = item.Faltas3Bim;
                            break;
                        case 4:
                            ViewBag.Nota = item.Conceito4Bim; ViewBag.Falta = item.Faltas4Bim;
                            break;
                    }

                }


                conceitos = _banco.Conceitos.Where(x => x.Matricula.AlunoId == alunoId).ToList();

                var novoaluno = _banco.Matriculas.FirstOrDefault(x => x.AlunoId == alunoId);

                var dadosaluno = conceitos.FirstOrDefault();

                var conform = _banco.ConceitoFormacaos.FirstOrDefault(x => x.Matricula.AlunoId == alunoId && periodo == x.Periodo);

                if(conform != null)
                {
                    ViewBag.FormConId = conform.Id;
                    ViewBag.AtitVal = conform.AtitVal;
                    ViewBag.CompAssid = conform.CompAssid;
                    ViewBag.CriCriti = conform.CriCriti;
                    ViewBag.PartFamilia = conform.PartFamilia;
                }

                if (dadosaluno != null)
                {
                    ViewBag.NomeAluno = dadosaluno.Matricula.Aluno.Nome;
                    ViewBag.AlunoId = dadosaluno.Matricula.AlunoId;
                    ViewBag.MatriculaId = dadosaluno.MatriculaId;
                    if (novoaluno != null) ViewBag.NovoAlunoId = novoaluno.AlunoId;
                    ViewBag.Turma = dadosaluno.Matricula.Turma.NomeTurma;
                    ViewBag.TurmaId = dadosaluno.Matricula.TurmaId;
                }
                ViewBag.Periodo = periodo;
            }


            return View(conceitos);
        }

        public ActionResult Index(int? turmaId, int? disciplinaId)
        {
            ViewBag.turmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma");

            var disciplina = (from d in _banco.Disciplinas
                              join dpt in _banco.DisciplinaDoProfessoresNasTurmas on d.Id equals dpt.DisciplinaId
                              where d.Id == dpt.DisciplinaId && dpt.TurmaId == turmaId
                              select d).ToList();

            ViewBag.DisciplinaId = new SelectList(disciplina, "Id", "NomeDisciplina");

            var conceitos = new List<Conceito>();

            //conceitos = (from con in _banco.Conceitos
            //             join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
            //             select con).ToList();


            if (turmaId != null && disciplinaId != null)
            {

                conceitos = (from con in _banco.Conceitos
                             join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
                             where con.MatriculaId == mat.Id && mat.TurmaId == turmaId && con.DisciplinaId == disciplinaId
                             select con).ToList();

            }


            return View(conceitos);
        }

        public ActionResult Detalhes(long id, int disciplinaId)
        {
            var conceito = _banco.Conceitos.FirstOrDefault(x => x.Id == id && x.DisciplinaId == disciplinaId);

            return View(conceito);
        }

        public ActionResult NotasTurma(int? turmaId, int? disciplinaId, int? periodo)
        {
            ViewBag.TurmaId = new SelectList(_banco.Turmas, "Id", "NomeTurma");

            var disciplinas = (from d in _banco.Disciplinas
                               join dpt in _banco.DisciplinaDoProfessoresNasTurmas on d.Id equals dpt.DisciplinaId
                               where d.Id == dpt.DisciplinaId && dpt.TurmaId == turmaId
                               select d).ToList();

            ViewBag.DisciplinaId = new SelectList(disciplinas, "Id", "NomeDisciplina");

            ViewBag.Bimestre = periodo;

            var bimestre = new List<Bimestre>();

            if (turmaId != null && disciplinaId != null)
            {
                //List<Matricula> semNota = (from mat in _banco.Matriculas
                //                           join con in _banco.Conceitos on mat.Id equals con.MatriculaId
                //                           into matricula
                //                           from con in matricula.DefaultIfEmpty()
                //                           where con.MatriculaId != mat.Id
                //                           select mat).ToList();

                List<Matricula> query = null;

                switch (periodo)
                {
                    case 1:
                        query = (from con in _banco.Conceitos
                                 join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
                                 where con.Matricula.TurmaId == turmaId &&
                                 con.DisciplinaId == disciplinaId &&
                                 con.Conceito1Bim == null
                                 select mat).ToList();

                        //query.AddRange(semNota);

                        break;

                    case 2:
                        query = (from con in _banco.Conceitos
                                 join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
                                 where con.Matricula.TurmaId == turmaId &&
                                 con.DisciplinaId == disciplinaId &&
                                 con.Conceito2Bim == null
                                 select mat).ToList();

                        //query.AddRange(semNota);
                        break;

                    case 3:
                        query = (from con in _banco.Conceitos
                                 join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
                                 where con.Matricula.TurmaId == turmaId &&
                                 con.DisciplinaId == disciplinaId &&
                                 con.Conceito3Bim == null
                                 select mat).ToList();

                        //query.AddRange(semNota);
                        break;

                    case 4:
                        query = (from con in _banco.Conceitos
                                 join mat in _banco.Matriculas on con.MatriculaId equals mat.Id
                                 where con.Matricula.TurmaId == turmaId &&
                                 con.DisciplinaId == disciplinaId &&
                                 con.Conceito4Bim == null
                                 select mat).ToList();

                        //query.AddRange(semNota);

                        break;
                }

                if (query != null)
                {
                    query = query.OrderBy(x => x.Aluno.Nome).ToList();

                    bimestre.AddRange(query.Select(item => new Bimestre
                    {
                        MatriculaId = item.Id,
                        Aluno = item.Aluno.Nome
                    }));
                }
            }

            return View(bimestre);
        }

        [HttpPost]
        public ActionResult NotasTurma(List<int> matriculaId, List<string> nota, List<string> falta, int disciplinaId, int periodo, int turmaId)
        {
            var i = 0;
            foreach (var aluno in matriculaId)
            {
                var matricula = _banco.Conceitos.FirstOrDefault(x => x.MatriculaId == aluno && x.DisciplinaId == disciplinaId);

                if (matricula != null)
                {
                    switch (periodo)
                    {
                        case 1:

ccb_web/Views/Conceito/ConceitoAluno.cshtml
@model IEnumerable<ccb_web.Models.Bimestre>
@{
    ViewBag.Title = "ConceitoAluno";
    Layout = "~/Views/Shared/_LayoutPadrao.cshtml";
    
}
<script>
    $(function () {
        $('#periodo').val("@ViewBag.Bimestre");
        $('#nota').val("@ViewBag.Nota");
        $('#falta').val("@ViewBag.Falta");
    });
</script>

<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Conceito do Aluno</strong>
</div>

<div class="panel-body">

    @using (@Html.BeginForm("ConceitoAluno", "Conceito", FormMethod.Get))
    {

        <div class="row">
            <div class="col-xs-4 col-md-4">
                <div class="form-group">
                    <label class="control-label">Turmas:</label>
                    @Html.DropDownList("TurmaId", (SelectList)ViewBag.TurmaId, "SELECIONE A TURMA", new { @class = "form-control", onchange = "this.form.submit();" })
                </div>
            </div>
            <div class="col-xs-4 col-md-4">
                <label class="control-label">Disciplina:</label>
                @Html.DropDownList("DisciplinaId", (SelectList)ViewBag.DisciplinaId, "SELECIONE A DISCIPLINA", new { @class = "form-control", onchange = "this.form.submit();" })
            </div>
            <div class="col-xs-4 col-md-4">
                <label class="control-label">Periodo:</label>
                <select id="periodo" class="form-control" name="periodo" onchange=" this.form.submit(); ">
                    <option value="">SELECIONE O PERIODO</option>
                    <option value="1">1º Bimestre</option>
                    <option value="2">2º Bimestre</option>
                    <option value="3">3º Bimestre</option>
                    <option value="4">4º Bimestre</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <label class="col-sm-2 control-label">Alunos:</label>
                    <div class="col-sm-10">
                        @Html.DropDownList("AlunoId", (SelectList)ViewBag.AlunoId, "SELECIONE O ALUNO", new { @class = "form-control", onchange = "this.form.submit();" })
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>

    }

    @using (@Html.BeginForm("ConceitoAluno", "Conceito", FormMethod.Post))
    {
        @Html.Hidden("turmaId")
        @Html.Hidden("disciplinaId")
        @Html.Hidden("periodo")
        @Html.Hidden("AlunoId")

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-xs-6 col-md-3">
                <label class="control-label">Nota:</label>
                <select id="nota" class="form-control" name="nota">
                    <option value="A">A</option>
                    <option value="B">B</option>
                    <option value="C">C</option>
                </select>
            </div>
            <div class="col-xs-6 col-md-3">
                <label class="control-label">Faltas:</label>
                <input type="text" class="form-control" name="falta" id="falta" />
            </div>
            <div class="col-md-3"></div>
        </div>

        <div class="row">
            <hr />
            <div class="col-xs-6 col-md-3 col-md-offset-6">
                <a class="btn btn-block btn-lg btn-danger" href="@Url.Action("ListaAluno", "Conceito")"><span class="glyphicon glyphicon-remove"></span>Cancelar</a>
            </div>
            <div class="col-xs-6 col-md-3">
                <button type="submit" class="btn btn-block btn-lg btn-success" value="Adicionar"><span class="glyphicon glyphicon-floppy-disk"></span>Cadastrar</button>
            </div>
        </div>
    }

</div>


<table class="table table-hover table-bordered">
    <tr>
        <th>Aluno
        </th>
        <th>Disciplina
        </th>
        <th>Nota
        </th>
        <th>Falta
        </th>
        <th>Periodo
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Aluno
            </td>
            <td>
                @item.Disciplina
            </td>
            <td>
                @item.Nota
            </td>
            <td>
                @item.Falta
            </td>
            <td>
                @item.Periodo
            </td>
        </tr>
    }

</table>

ccb_web/Views/Conceito/Detalhes.cshtml
@model ccb_web.Models.Conceito

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_LayoutPadrao.cshtml";
}

<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Detalhes</strong>
</div>

<div class="panel-body">



    <table class="table table-bordered">
        <tr>
            <th colspan="2"></th>
            <th colspan="2">1º Bimestre</th>
            <th colspan="2">2º Bimestre</th>
            <th colspan="2">3º Bimestre</th>
            <th colspan="2">4º Bimestre</th>
        </tr>
        <tr>
            <th>Aluno</th>
            <th>Disciplina</th>
            <th>Nota</th>
            <th>Faltas</th>
            <th>Nota</th>
            <th>Faltas</th>
            <th>Nota</th>
            <th>Faltas</th>
            <th>Nota</th>
            <th>Faltas</th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Matricula.Aluno.Nome)
            </td>
            <td>
                @Html.DisplayFor(model => model.Disciplina.NomeDisciplina)
            </td>
            <td>
                @Html.DisplayFor(model => model.Conceito1Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Faltas1Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Conceito2Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Faltas2Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Conceito3Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Faltas3Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Conceito4Bim)
            </td>
            <td>
                @Html.DisplayFor(model => model.Faltas4Bim)
            </td>
        </tr>
    </table>
    <div class="row">
        <hr />
        <div class="col-md-3 col-md-offset-6">
            <a class="btn btn-block btn-lg btn-danger" href="@Url.Action("Index", "Conceito")">
                <span class="glyphicon glyphicon-chevron-left"></span><span>&nbsp;</span>Voltar
            </a>
        </div>
        <div class="col-md-3">
            <a class="btn btn-block btn-lg btn-warning" href="@Url.Action("ConceitoAluno", "Conceito", new { turmaId = Model.Matricula.TurmaId, disciplinaId = Model.DisciplinaId, alunoId = Model.MatriculaId, periodo = 1})">
                <span class="glyphicon glyphicon-edit"></span><span>&nbsp;</span>Editar
            </a>
        </div>
    </div>





    @*    <fieldset>
    <legend>Conceito</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DisciplinaId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DisciplinaId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Matricula.Aluno.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Matricula.Aluno.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Conceito1Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Conceito1Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Conceito2Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Conceito2Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Conceito3Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Conceito3Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Conceito4Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Conceito4Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ConceitoFinal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ConceitoFinal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Faltas1Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Faltas1Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Faltas2Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Faltas2Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Faltas3Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Faltas3Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Faltas4Bim)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Faltas4Bim)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FaltasTotal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FaltasTotal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Situacao)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Situacao)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Editar", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@
</div>

ccb_web/Views/Conceito/GerenciarNotasTurma.cshtml
@model List<ccb_web.Models.Conceito>
@{
    ViewBag.Title = "GerenciarNotasTurma";
}

<script>
    $(document).ready(function () {
        $('#turmaId').addClass("form-control");
        $('#DisciplinaId').addClass("form-control");
    });
</script>

<h2>GerenciarNotasTurma</h2>

@using (@Html.BeginForm("GerenciarNotasTurma", "Conceito", FormMethod.Get))
{
    <div>
        @Html.DropDownList("turmaId", (SelectList)ViewBag.turmaId, "Selecione a turma", new { onchange = "this.form.submit();" })
    </div>

    <div>
        @Html.DropDownList("DisciplinaId", (SelectList)ViewBag.DisciplinaId, "Selecione a disciplina", new { onchange = "this.form.submit();" })
    </div>
    
    <div>
        <select class="form-control" name="etapa" id="etapa" onchange="this.form.submit();">
            <option value="1">1º Bimestre</option>
            <option value="2">2º Bimestre</option>
            <option value="3">3º Bimestre</option>
            <option value="4">4º Bimestre</option>
        </select>
    </div>
}

<hr />

@using (@Html.BeginForm("GerenciarNotasTurma", "Conceito", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.Hidden("turmaId")
    @Html.Hidden("DisciplinaId")

    <table class="table table-bordered">
        <tr>
            <th></th>
            <th colspan="2">1º Bimestre</th>
            <th colspan="2">2º Bimestre</th>
            <th colspan="2">3º Bimestre</th>
            <th colspan="2">4º Bimestre</th>

        </tr>
        <tr>
            <th>Aluno
            </th>
            <th>Nota
            </th>
            <th>Falta
            </th>
            <th>Nota
            </th>
            <th>Falta
            </th>
            <th>Nota
            </th>
            <th>Falta
            </th>
            <th>Nota
            </th>
            <th>Falta
            </th>
        </tr>


        @if (Model != null)
        {
            foreach (var item in @Model)
            {
            <tr>
                <td class="col-md-4">
                    <input type="hidden" value="@item.Id" name="id" id="id"/>
                    <input type="hidden" value="@item.Matricula.Id" name="Matricula" id="Matricula"/>
                    @item.Matricula.Aluno.Nome
                </td>

                <td class="col-md-1">
                    <input type="text" name="Conceito1Bim" id="Conceito1Bim" class="form-control" value="@item.Conceito1Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Faltas1Bim" id="Faltas1Bim" class="form-control" value="@item.Faltas1Bim"/>

                </td>
                <td class="col-md-1">
                    <input type="text" name="Conceito2Bim" id="Conceito2Bim" class="form-control" value="@item.Conceito2Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Faltas2Bim" id="Faltas2Bim" class="form-control" value="@item.Faltas2Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Conceito3Bim" id="Conceito3Bim" class="form-control" value="@item.Conceito3Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Faltas3Bim" id="Faltas3Bim" class="form-control" value="@item.Faltas3Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Conceito4Bim" id="Conceito4Bim" class="form-control" value="@item.Conceito4Bim"/>
                </td>
                <td class="col-md-1">
                    <input type="text" name="Faltas4Bim" id="Faltas4Bim" class="form-control" value="@item.Faltas4Bim"/>
                </td>

            </tr>
            }
        }

    </table>
    
    <button type="submit" class="btn btn-lg btn-block btn-success"><span class="glyphicon glyphicon-floppy-disk"></span>Gravar</button>
}

ccb_web/Views/Conceito/Index.cshtml
@model IEnumerable<ccb_web.Models.Conceito>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutLista.cshtml";
}
<script>
    $(document).ready(function () {
        $('#turmaId').addClass("form-control");
        $('#DisciplinaId').addClass("form-control");
    });
</script>


<div class="panel panel-heading">
    <strong><span class="glyphicon glyphicon-cog"></span><span>&nbsp;</span>Conceito</strong>
</div>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class=" panel panel-success">

                <div class="panel-heading">
                    <p>
                        <a href="@Url.Action("ConceitoAluno", "Conceito")" class="btn btn-block btn-lg btn-success"><span class="fa fa-plus"></span><span>&nbsp;</span>Novo Conceito</a>
                    </p>


                    @using (@Html.BeginForm(FormMethod.Get))
                    {

                        <div>
                            @Html.DropDownList("turmaId", (SelectList)ViewBag.turmaId, "Selecione a turma", new { onchange = "this.form.submit();" })
                        </div>

                        <div>
                            @Html.DropDownList("DisciplinaId", (SelectList)ViewBag.DisciplinaId, "Selecione a disciplina", new { onchange = "this.form.submit();" })
                        </div>
                    }

                </div>
                <table class="table table-hover table-bordered">
                    <tr>
                        <th>
                            Turma
                        </th>
                        <th>
                            Aluno
                        </th>

                        <th>
                            AÇÕES
                        </th>

                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Matricula.Turma.NomeTurma)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Matricula.Aluno.Nome)
                            </td>

                            <td>
                                <a class="btn btn-primary btn-warning" title="Editar" href="@Url.Action("GerarHistoricoAluno", "HistoricoAluno", new { item.Matricula.Aluno.Id })">
                                    <span class="fa fa-edit"></span>
                                </a>

                                @*<a class="btn btn-primary btn-info" title="Detalhes" href="@Url.Action("Detalhes", "Conceito", new { id = item.Id, disciplinaId = item.DisciplinaId })">
                                        <span class="glyphicon glyphicon-list-alt"></span>
                                    </a>

                                    <a class="btn btn-primary btn-danger" title="Excluir" href="@Url.Action("Excluir", "Conceito", new { id = item.Id })">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>*@
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>

ccb_web/Views/Conceito/ListaAluno.cshtml
@model PagedList.IPagedList<ccb_web.Models.Matricula>
@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Lista";
    Layout = "~/Views/Shared/_LayoutLista.cshtml";

}
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.11.4.js"></script>
<script type="text/javascript">
    $(function () {
        $("#termoBusca").autocomplete({
            source: '@Url.Action("GetAlunos")'
        });
    });
</script>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-4">
                        <h5>Alunos Cadastrados</h5>
                    </div>
                    <div class="col-md-8">
                        @using (@Html.BeginForm("ListaAluno", "Conceito", FormMethod.Post))
                        {
                            <div class="input-group">
                                <input type="text" class="form-control" name="termoBusca" id="termoBusca" placeholder="Buscar por...">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-default">Buscar <span class="fa fa-search"></span></button>
                                </span>
                            </div>
                        }
                    </div>
                </div>
            </div>
            
                <table class="table table-hover">
                    <tr>
                        <th>
                            Nome Aluno
                        </th>
                        <th>
                            Nascimento
                        </th>
                        <th>
                            AÇÕES
                        </th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Aluno.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Aluno.DataNascimento)
                            </td>
                            <td>
                                <a class="btn btn-default" title="Conceito" href="@Url.Action("NotaAluno", "Conceito",  new {alunoId = item.AlunoId, periodo = 1})">
                                    <div><i class="fa fa-book fa-fw text-danger" aria-hidden="true"></i>CONCEITO</div>
                                </a>
                            </td>
                        </tr>
                    }
                </table>
            <div class="panel-footer">
                <div class="text-center">
                    @Html.PagedListPager(Model, page => Url.Action("ListaAluno", new { pagina = page }))
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery.confirm.js"></script>
<script>
    $(".confirm").confirm({
        text: "Tem certeza que deseja excluir?",
        confirmButton: "Sim",
        cancelButton: "Não"
    });
</script>